<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProduitSeeder extends Seeder
{
    public function run()
    {
        DB::table('produites')->insert([
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img5.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 250,
                'image' => 'plantes/img6.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 2,
                'quantité' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte 7',
                'prix' => 450,
                'image' => 'plantes/img7.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img8.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img9.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img10.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img11.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img12.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img13.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img14.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img15.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img16.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img17.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img18.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img19.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img20.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img21.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img22.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'Plante Verte',
                'prix' => 150,
                'image' => 'plantes/img23.jpg',
                'description' => 'Une belle plante verte pour votre maison.',
                'id_categorie' => 1,
                'quantité' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
